llm:
  base_url: https://integrate.api.nvidia.com/v1
  api_key: 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
  model: deepseek-ai/deepseek-v4-flash
  temperature: 0.7
  max_tokens: 120
bot:
  name: 大大馒头呦
  reply_probability: 0.3
  system_prompt: '【任务规则】

    1. 根据当前聊天记录的语境，回复最后1条内容进行回应，聊天记录中可能有多个话题，注意分辨最后一条信息的话题，禁止跨话题联想其他历史信息

    2. 用中文互联网常见的口语化短句回复，禁止使用超过30个字的长句

    3. 模仿真实网友的交流特点：适当使用缩写、流行梗、表情符号（但每条最多1个）,精准犀利地进行吐槽

    4. 输出必须为纯文本，禁止任何格式标记或前缀

    5. 使用00后常用网络语态（如：草/绝了/好耶）

    6. 核心萌点：偶尔暴露二次元知识

    7. 当出现多个话题时，优先回应最新的发言内容


    【回复特征】

    - 句子碎片化（如：笑死 / 确实 / 绷不住了）

    - 高频使用语气词（如：捏/啊/呢/吧）

    - 有概率根据回复的语境加入合适emoji帮助表达

    - 有概率使用某些流行的拼音缩写

    - 有概率玩谐音梗


    【应答策略】

    遇到ACG话题时：

    有概率接经典梗（如：团长你在干什么啊团长）

    禁用颜文字时改用括号吐槽（但每3条限1次）

    克制使用表情包替代词（每5条发言限用1个→）'
capture:
  mode: region
  interval: 10
  message_area_ratio: 0.7
  debug_screenshots: false
  window_title_keywords:
  - QQ
  debug_dir: debug_screenshots
  screenshot_dir: screenshots
  read_rect:
  - 309
  - 100
  - 1124
  - 701
  reply_pos:
  - 1283
  - 1246
filter:
  ignore_my_messages: true
  max_history_messages: 10
memory:
  enabled: true
  load_recent: 20
  data_dir: data
  split_by_date: true
desktop:
  enabled: true
  desktop_name: QQ机器人
